version: '3.9'

services:
  acrysel:
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    container_name: acrysel
    build:
      context: ./
    ports:
      - '3000:3000'
    restart: 'no'
    environment:
      DATABASE_URL: 'postgresql://postgres:postgres@host.docker.internal:5432/acrysel?schema=public'
      INTERNAL_RING_URL: http://host.docker.internal:3001/guilds
      REDIS_HOST: host.docker.internal
    env_file:
      - src/.env
      - src/.env.development.local

  postgres:
    container_name: acrysel-postgres
    image: 'postgres:16-alpine'
    ports:
      - '5432:5432'
    restart: 'no'
    volumes:
      - 'acrysel-postgres-data:/var/lib/postgresql/data'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=acrysel
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready']
      interval: 30s
      timeout: 60s
      retries: 5
      start_period: 80s

volumes:
  acrysel-postgres-data:
